services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN- }
      - LAMBDA_REMOTE_DOCKER=0
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  grafana:
    image: grafana/grafana-enterprise
    user: '0'
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - AWS_ACCESS_KEY_ID=$LOCALSTACK_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$LOCALSTACK_SECRET_ACCESS_KEY
    volumes:
      - '$PWD/grafana-data:/var/lib/grafana'
      - '$PWD/grafana/provisioning/:/etc/grafana/provisioning/'